# Generated by Django 4.2.3 on 2023-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_clients_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
