# Generated by Django 4.2.3 on 2023-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clients_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
