# Generated by Django 4.2.3 on 2023-08-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clients_football_dice_clients_roleta_evo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='football',
            new_name='football_studio',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='roleta',
            new_name='roleta_playtech',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='roleta_playtec',
        ),
    ]
