# Generated by Django 4.2.3 on 2023-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_football_clients_football_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='bet_betano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='bet_blaze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='bet_brxbet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='bet_estrelabet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='bet_saurobet',
            field=models.BooleanField(default=False),
        ),
    ]
