# Generated by Django 4.2.3 on 2023-09-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clients_bet_betano_clients_bet_blaze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='bet_blaze',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='bet_estrelabet',
            field=models.BooleanField(default=True),
        ),
    ]
